### PR TITLE
Fix problems with pattern files

### PR DESCRIPTION
**Pull request by 314eter**
Some small fixes:

- The `files` input should not be required anymore, since you can use `files-list` instead.
- According to the [documentation](https://github.com/actions/toolkit/tree/main/packages/core#annotations), you can't use `startColumn` and `endColumn` when `startLine` and `endLine` are different.
- I changed `failures` back to an array instead of a set. Sets don't support `.join()`.
- Tree-sitter doesn't resolve patterns in the `--paths` file, so we should do that first.
- If there are a lot of parsed files, it's easier if the results are logged in a separate group, so you can keep the full tree-sitter output closed if you don't need it.

Example run: https://github.com/314eter/tree-sitter-ocaml/actions/runs/8316887538
(the Windows failures are already fixed on master, I left them here for testing)

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
> The `files` input should not be required anymore, since you can use `files-list` instead.

But at least one of the two *is* required.

> I changed `failures` back to an array instead of a set. Sets don't support `.join()`.

`Array.from(set).join()` works.

> If there are a lot of parsed files, it's easier if the results are logged in a separate group, so you can keep the full tree-sitter output closed if you don't need it.

There is no tree-sitter output.

**Comment by 314eter** [comment]
You removed the pattern expansion with your refactor. The content of the `files-list` file is not expanded anymore. I introduced the difference between the `patternsFile` and `pathsFile` to make it clear that you can't pass patterns via `--paths`.

> But at least one of the two is required.

It works if you don't provide either of them, it's just not very useful.

> `Array.from(set).join()` works

True. I just did't see any reason to use a set, since we don't need any of its features and it's slower. Now you're converting the set to an array twice. And you forgot to replace one `failures.length` by `failures.size`.

> There is no tree-sitter output.

There is, because of the `-t` flag. See https://github.com/314eter/tree-sitter-ocaml/actions/runs/8316887538/job/22756954711. Removing that flag is fine too for me.

**Comment by ObserverOfTime** [comment]
> The content of the `files-list` file is not expanded anymore.

The files should not contain globs. I'll clarify that.

> True. I just did't see any reason to use a set, since we don't need any of its features and it's slower. Now you're converting the set to an array twice.

We need the uniqueness and it's not significantly slower.

> There is, because of the `-t` flag.

Try 67407be. The output should be silent and logged with `info()` now.

**Comment by ObserverOfTime** [comment]
> The files should not contain globs. I'll clarify that.

Changed my mind. Fixed in 53ef75e.

**Comment by 314eter** [comment]
> We need the uniqueness and it's not significantly slower.

I don't see how there can ever be duplicate entries, but you can use a set if you want.

> The output should be silent and logged with info() now.

Personally, I wouldn't log the successful ones at all. If there are thousands of successful files and only a few failures, it's annoying to have so many useless log lines.

**Comment by ObserverOfTime** [comment]
> Personally, I wouldn't log the successful ones at all. If there are thousands of successful files and only a few failures, it's annoying to have so many useless log lines.

The logs are there to check the parsing times. Look at the summary for failures.

**Pull request merged**
