### PR TITLE
fix: expand patterns in file

### PR DESCRIPTION
**Pull request by 314eter**
`patternsFile` was not being used.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Made it a function.

**Comment by 314eter** [comment]
The `patternsFile` in `action.getInput('files', { required: !patternsFile })` doesn't exist.

**Comment by ObserverOfTime** [comment]
Ah shit. Fixed it.

**Comment by 314eter** [comment]
Ok. Works now: https://github.com/tree-sitter/tree-sitter-ocaml/pull/87

One peculiarity that is maybe not obvious for everyone, is that the `files` and `files-list` patterns are expanded separately. So you can't do `files: examples/**/*.ext` and then add exclusions in `files-list`. Maybe it's good to mention that in the documentation, or even recommend not to combine `files` and `files-list`.

**Comment by ObserverOfTime** [comment]
Won't tree-sitter handle the exclusions?

**Comment by 314eter** [comment]
No, we're passing a file with paths to tree-sitter, not patterns.

The behaviour of negated patterns depends on the order. They can only exclude files that were included before, not after. So if you want to combine `files` and `files-list` in a single "pattern collection", the order in which you do so becomes important.

I don't really see a use case for having both `files` and `files-list`, and the consequences can be confusing. Not allowing it at all is an option too.

**Comment by ObserverOfTime** [comment]
I'll figure something out tomorrow.

**Comment by ObserverOfTime** [comment]
Can you try v4?

**Comment by 314eter** [comment]
As I said before, I don't think it's a good idea to combine the patterns like that.

With your new implementation, this will work as expected:
```yaml
files: |
  examples/**/*.ext
files-list: files.txt
```
```
files.txt
---------
!examples/invalid1.ext
!examples/invalid2.ext
```

But this will not work
```yaml
files-list: files.txt
files: |
  !examples/invalid1.ext
  !examples/invalid2.ext
```
```
files.txt
---------
examples/**/*.ext
```

**Comment by ObserverOfTime** [comment]
That seems like a limitation of `@actions/glob` and there's nothing I can do about it.

**Comment by 314eter** [comment]
That's not a limitation of `@actions/glob`, it's how [git patterns](https://git-scm.com/docs/gitignore#_pattern_format) are supposed to work.

But it does mean that the combination of `files` with `files-list` doesn't make sense. So it's a lot better to give a clear error message when someone tries to use them both (for which I don't see a use case), than to try to support it and do it badly.

**Pull request merged**
