### PR TITLE
Improve performance and add invalid-files-list option

### PR DESCRIPTION
**Pull request by 314eter**
I'm trying to use this action for [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml), and had some issues:

- it's very slow because every file is parsed in a new process
- providing the list of invalid files in the workflow configuration makes it difficult to reuse in a script that runs locally

By passing the patterns directly to a single tree-sitter command, the total execution time is 10 times faster. I added a new `invalid-files-list` option to pass a file with patterns instead of the patterns themselves.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
The problem is that there's a limit to the number of arguments you can pass to a command.
I do have another solution in mind though.

**Comment by 314eter** [comment]
I don't really expect that to be a problem, since in most cases the `files` patterns will be just `examples/**/*.ext` for each supported extension. If necessary, it's possible to pass the patterns one by one, but the `!` patterns will have to be included every time.

Another option is to add support in `tree-sitter-cli` for passing patterns in a file or stdin.

**Comment by ObserverOfTime** [comment]
> in most cases the `files` patterns will be just `examples/**/*.ext` for each supported extension

Which is expanded into all the matches.

> Another option is to add support in `tree-sitter-cli` for passing patterns in a file or stdin.

That's already supported and what I'll go for.

**Comment by 314eter** [comment]
> Which is expanded into all the matches.

It would be expanded into separate command line arguments if you execute it in a shell. But here it's passed directly to `exec()` as a single argument, and it's `tree-sitter` doing the expansion. Otherwise it wouldn't be able to pass 12231 files to windows [here](https://github.com/314eter/tree-sitter-ocaml/actions/runs/8311714280).

> That's already supported and what I'll go for.

Aha, I completely missed that. Are you already implementing that, or should I update this PR?

**Comment by ObserverOfTime** [comment]
I'm implementing it and I'll incorporate your changes.

**Comment by ObserverOfTime** [comment]
Closed in commit c7edd47. Try that in ocaml.

**Pull request closed without merging**
